### PR TITLE
Updated Polish Block Translations

### PR DESCRIPTION
**Pull request by wrata**
Polish Block Translations

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks very much for the translation. I will generate a new release with your changes.

**Comment by MrYsLab** [comment]
@wrata I am updating the wiki pages with the new blocks. I should have this done within a day or two and then will create a new release to put on pypi. Thanks again.

**Comment by wrata** [comment]
Thank you for placing my work in your project. I will prepare a few more examples in Polish and I will popularize the a2aio project among Polish teachers.

**Comment by MrYsLab** [comment]
I have just released version 1.17. It is available on pypi. Thanks again.

**Comment by wrata** [comment]
Thank you. I have already used this installation today.

**Pull request merged**
