### PR TITLE
Charset Parameter should be on its own, otherwise Exception is thrown.

### PR DESCRIPTION
**Pull request by mirko314**
Walked into an Exception because of this. Seems to work when Parameter is on its own.

### CODE REVIEW

**Comment by MrYsLab** [comment]
Since I do not get an exception could you please provide some additional information so that I can try to reproduce it. 
1. Are you starting s2aio with any command line options, and if so what are they?
2. Are you using Scratch or Snap?
3. Are you loading a set of blocks that are something other than English and if so, what language are you using?

Thanks.

**Comment by mirko314** [comment]
Well just now im unable to reproduce the Exception. But If you look at the aiohttp Library:

``` python
                elif ";" in content_type:
                    raise ValueError('charset must not be in content_type '
                                     'argument')
                charset = charset or 'utf-8'
```

> https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py
> Line 751

It should throw an exception when charset is in the same argument.
1. No Commandline Arguments were used
2. Scratch
3. Yes normally used scratch_DE, But should not matter that much.

Kind Regards

**Comment by MrYsLab** [comment]
It appears that aiohttp was changed on October 26 for version 0.19.0. Thanks for letting me know

**Comment by MrYsLab** [comment]
@mirko314  If you do a pip install s2aio --upgrade, you should get all the latest changes. Thanks again.

**Comment by mirko314** [comment]
You are welcome. Thank you, MrYsLab, for the many improvements!
Upgrade worked.

**Pull request merged**
